### ISSUE TITLE
pdf-util-0.0.1.jar contains dependency classes

### ISSUE THREAD

**Issue by PascalSchumacher** [vinsguru/pdf-util#1]
Hi,

thanks for providing pdf-util. :+1: 

We had some problems using pdf-util, because the jar contains the classes of the dependencies. Our project is using `commons-io 2.5` but pdf-util uses `commons-io 1.3.2` and pdf-util adds these classes to the classpath.

Please consider removing the classes from the jar or use the maven shade plugin to relocated the classes (see: https://maven.apache.org/plugins/maven-shade-plugin/examples/class-relocation.html for details;  I could send you a pull request, if you like.)

Both solutions will prevent dependency conflicts.

**Comment by vinsguru** [comment]
Updated dependencies. New version 0.0.2 is available in mvn repo.
