### ISSUE TITLE
PDF Comparison failing though both PDFs are same because on non sequencial retrival of text

### ISSUE THREAD

**Issue by madhur-dumane** [vinsguru/pdf-util#8]
I am using below code to get whole PDF text into strings and then compare of both string.
String str = pdfutil.getText("C:\\Users\\"+System.getProperty("user.name")+"\\Downloads"+"\\"+prereport+".pdf");
String str1 = pdfutil.getText("C:\\Users\\"+System.getProperty("user.name")+"\\Downloads"+"\\"+postreport+".pdf");
System.out.println("Check the text from both PDFs : " + str.equalsIgnoreCase(str1));

sometimes retrival of text is not sequencial.Ex-		
suppose from 1 PDF its retrieved text like ---   $497.10 0.51 - Investment Cash
from 2nd PDF its retrieving text like --- $497.10 -0.51 Investment Cash

in one string there is 0.51 - and in other string -0.51 so PDF comparison is failing. 
![pdfcontent](https://user-images.githubusercontent.com/33079492/31981138-d4e0d4b2-b916-11e7-8768-54ae031b475c.PNG)
Please see above screenshot how it looks in actual both PDFs. Ideally it should retrieve sequentially and PDF Comparison should be successfully .Please help me to resolve this issue.

**Comment by vinsguru** [comment]
Use mvn version `0.0.3`

I have modified to use your own Stripper using pdfbox.  Below sample code should retrieve the text based on the position.

```
        PDFTextStripper stripper = new PDFTextStripper();
        stripper.setSortByPosition(true);
        pdfutil.useStripper(stripper);
        
       pdfutil.getText(filePath);
```

**Comment by madhur-dumane** [comment]
I have not changed maven version but using above code it is working.
Thank you so much for your help

**Comment by vinsguru** [comment]
Glad that it worked
